    # print('\nMedidas de tendência central: ')
    # print(30*'-')
    # print(f'Média de roubo de veículos: {media_roubo_veiculo}')
    # print(f'Mediana de roubo de veículos: {mediana_roubo_veiculo}')
    # print(f'Distância entre média e mediana: {distancia:.3f}')